apiVersion: v1
kind: Service
metadata:
  name: azure-back-service
spec:
  type: LoadBalancer
  ports:
    - port: 3000
  selector:
    app: azure-back-app

---

apiVersion: v1
kind: Service
metadata:
  name: azure-front-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: azure-front-app